#!/bin/bash

DIR=$(pwd)

LINKS=(
	.alacritty.yml
	.archey3.cfg
	.bash_profile
	.bashrc
	bin/bash-history-sqlite.sh
	bin/bash-preexec.sh
	bin/bash-tagsearch.sh
	bin/commandstats
	bin/dark
	bin/dbhist.py
	bin/git-when-merged
	bin/imap-pass
	bin/light
	bin/monitor-internet
	bin/mutt-notmuch-py
	bin/newmirrors
	bin/paste
	bin/post-email-hook
	bin/sbrennan-setup
	bin/synchronize_namedqueries.py
	bin/tagsearch-preview.sh
	bin/urlc
	bin/urls
	bin/viewchain
	bin/wait-for-internet
	bin/widevine-update
	bin/yank
	.config/aerc/accounts.conf
	.config/aerc/aerc.conf
	.config/aerc/binds.conf
	.config/afew/config
	.config/alot/config
	.config/alot/themes/solarized_dark
	.config/alot/themes/solarized_light
	.config/notmuchqueries.json
	.config/nvim/init.vim
	.config/systemd/mbsync.service
	.config/systemd/mbsync.timer
	.config/tmux/tmuxcolors-dark.conf
	.config/tmux/tmuxcolors-light.conf
	.doom.d
	.gitconfig
	.hgrc
	.lc.json
	.mutt/account_stephen
	.mutt/mailcap
	.mutt/mutt-solarized-dark-16.muttrc
	.mutt/vim-keys.rc
	.profile
	.spacemacs
	.spacemacs.d/snippets
	.ssh/authorized_keys
	.ssh/config
	.tmux.conf
	.vim
	.vimrc
	.xprofile
	.Xresources
	.Xresources.d/solarized.dark
	.Xresources.d/solarized.light
)

M4_LINKS=(
	.msmtprc
	.mbsyncrc
	.mutt/muttrc
	bin/lc
)

create_symlink() {
	full_home=$HOME/$1
	full_local=$DIR/$1
	mkdir -p $(dirname $full_home)
	rm -f $full_home
	echo -e "LINK\t$1"
	ln -s $full_local $full_home
}

M4_CONTEXT=""

# Add OS to M4 Context
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]] ; then
	M4_CONTEXT="$M4_CONTEXT -DOS=linux"
elif [[ "$unamestr" == 'Darwin' ]]; then
	M4_CONTEXT="$M4_CONTEXT -DOS=mac"
else
	M4_CONTEXT="$M4_CONTEXT -DOS=unknown"
fi


echo "M4 Context:$M4_CONTEXT"
echo

for item in "${M4_LINKS[@]}"
do
	echo -e "M4\t$item"
	m4 $M4_CONTEXT "$item.m4" > $item
	create_symlink $item
done

for item in "${LINKS[@]}"
do
	create_symlink $item
done

chmod u+x ~/bin/lc
