#!/bin/bash

DIR=$(pwd)

LINKS=(
)

M4_LINKS=(
	.msmtprc
	.mbsyncrc
)

create_symlink() {
	full_home=$HOME/$1
	full_local=$DIR/$1
	mkdir -p $(dirname $full_home)
	rm -f $full_home
	echo -e "LINK\t$1"
	ln -s $full_local $full_home
}

M4_CONTEXT=""

# Add OS to M4 Context
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]] ; then
	M4_CONTEXT="$M4_CONTEXT -DOS=linux"
elif [[ "$unamestr" == 'Darwin' ]]; then
	M4_CONTEXT="$M4_CONTEXT -DOS=mac"
else
	M4_CONTEXT="$M4_CONTEXT -DOS=unknown"
fi


echo "M4 Context:$M4_CONTEXT"
echo

for item in "${M4_LINKS[@]}"
do
	echo -e "M4\t$item"
	m4 $M4_CONTEXT "$item.m4" > $item
	create_symlink $item
done

for item in "${LINKS[@]}"
do
	create_symlink $item
done
